### ISSUE TITLE
more info pls

### ISSUE THREAD

**Issue by stepir** [blauret/tyrePressureTracker#1]
Hi @blauret

I'm looking too to implement TPMS to HA and found your project? what it the current status of the code? do you have BT sensor to recommend and have been already tested? 

TIA

**Comment by blauret** [comment]
Hi @stepir,

It's working fine for me but I need to push some of the updates I'm currently running. 

With regards to the sensors, I'm using the sensors you can find on aliexpress when you search "bluetooth tpms". Most of them are using the same application. The problem is I'm bought a bunch of older generation ones and they have slightly changed the protocol. One of my colleague has written the code for those, I would need to merge that too. 

If I forget, ping again me around mid next week. I should be able to give you more details.

**Comment by stepir** [comment]
Great thanks!

curious as I never tried BT sensor before - I guess once you use HA integration you won’t be able to use the native app anymore right?meaning the BT sensor will connect only to the first reader?

**Comment by blauret** [comment]
Those sensors don't connect. They just advertise the data. So you can keep using the app. The problem with that is when they are inactive, the won't wake up for 10 min. So you can wait the data for a long time. What triggers a wake up is a movement or a change in pressure.

**Comment by stepir** [comment]
Thanks!

**Comment by stepir** [comment]
hey @blauret sorry to bother again!

wanted to check if you have some idea on the following: I bought some TESLA BLE sensors (it was not cheap but I needed the valve in metal as they will be used on a RV) - they are manufactured from SYSGRATION and substantially identical to this one https://www.sysgration.com/zh-tw/ble-tpms-sensor/ev-solution - I'm trying to test them with one of the many IOS app for BLE TPMS but all of them are asking a QR code for identifying the sensor  and inflation identification is not working either. I was able to capture the following with a BT scanner:

19:06:35.4050: connected in underlying BLE layer.
19:06:35.4230: discovered services: (
    "00000211-B2D1-43F0-9B88-960CEBF8B91E",
    1122
)
19:06:35.4450: discovered characteristics for service 00000211-B2D1-43F0-9B88-960CEBF8B91E: (
    "00000212-B2D1-43F0-9B88-960CEBF8B91E",
    "00000213-B2D1-43F0-9B88-960CEBF8B91E",
    "00000214-B2D1-43F0-9B88-960CEBF8B91E"
)
19:06:35.4460: state changed to 'Connected'.
19:06:41.7270: disconnected in underlying BLE layer with error: Error Domain=CBErrorDomain Code=6 "The connection has timed out unexpectedly." UserInfo={NSLocalizedDescription=The connection has timed out unexpectedly.}
19:06:41.7280: state changed to 'Disconnected' with error: The connection has timed out unexpectedly.

do you have any idea of which of the above could be (or a way to gather such) the 5 digit ID of the sensor?

Thanks a lot for your help!

[BSI03.pdf](https://github.com/blauret/tyrePressureTracker/files/8304588/BSI03.pdf)

**Comment by stepir** [comment]
other info if might of help

![image](https://user-images.githubusercontent.com/36472935/159016505-0821f73f-6152-4ae9-888b-7a0b68d51d5e.png)

14:53:12.452 - Characteristic (00000213-B2D1-43F0-9B88-960CEBF8B91E) notified: <1207e201 04086410 30> 
14:53:13.454 - Characteristic (00000213-B2D1-43F0-9B88-960CEBF8B91E) notified: <1211ea01 0e0a0432 68ef3e12 031c34d7 18bf17> 
14:54:12.451 - Characteristic (00000213-B2D1-43F0-9B88-960CEBF8B91E) notified: <120b9202 0808f429 10ba0318 01> 
14:58:12.451 - Characteristic (00000213-B2D1-43F0-9B88-960CEBF8B91E) notified: <120c9202 0908fac0 01108913 1801> 
15:02:12.464 - Characteristic (00000213-B2D1-43F0-9B88-960CEBF8B91E) notified: <120c9202 0908aeba 0210a940 1801> 
15:06:12.440 - Characteristic (00000213-B2D1-43F0-9B88-960CEBF8B91E) notified: <120c9202 0908c3a9 0310e977 1801>

**Comment by blauret** [comment]
I have no knowledge about these sensors. I have no idea about the protocol used or if they need connection or if the data is in the advertisement. I'm afraid I can't help with that.

**Comment by stepir** [comment]
Thanks anyway for answering!
